account/urls.py
from django.urls import path, include
from account import views

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

ecommercepr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt import views as jwt_views
from product import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('account/', include('account.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/account/', include('account.api.urls')),
    path('api/product/', include('product.api.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path, include
from product import views

app_name = 'product'

urlpatterns = [
    path('detail/<int:id>/', views.DetailView.as_view(), name='detail'),
    path('basket/', views.BasketView.as_view(), name ="basket"),
    path('favorite_delete/<int:id>/', views.favorite_delete, name="favorite_delete"),
]

templates/basket.html
{% extends 'components/base.html' %}

{% block head %} <title>Basket</title> {% endblock %}

{% block content %}
<p><div class="container text-primary"><h1>Səbətdəkilər</h1></div></p>
{% if request.user.is_authenticated %}
{% if user_favorites %}
{% for user_favorite in user_favorites %}

<div class="container mt-5">
  <div class="card mb-3" style="max-width: 50%;">
    <div class="row g-0">
      <div class="col-md-4">
        <a href="{% url 'product:detail' user_favorite.product.id %}"><img src="{{user_favorite.product.photo.url}}" class="img-fluid rounded-start" alt="{{user_favorite.product.name}}"></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{user_favorite.product.name}}<a href="{% url 'product:favorite_delete'  user_favorite.product.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="650" height="25" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
              <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
            </svg></a></h5>
            <h5 class="card-title">{{user_favorite.product.price}} azn</h5>
            <p class="card-text">{{user_favorite.product.about}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}
{% endif %}

{% endblock %}

templates/detail.html
{% extends 'components/base.html' %}

{% block head %} <title>Details</title> {% endblock %}

{% load datesince %}

{% block content %}
<div class="container mt-5">
  <div class="card mb-3" style="max-width: 100%;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{product.photo.url}}" class="img-fluid rounded-start" alt="{{product.name}}">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <h5 class="card-title">{{product.price}} azn</h5>
          <p class="card-text">{{product.about | design}}</p>
          <!-- <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p> -->
          <p>Baxış sayı: {{product.views_number}}</p>

          <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="choice" value="like">
            <input type="hidden" name="productid" value="{{product.id}}">
            {% if request.user.is_authenticated %}
            <button class="btn btn-primary" type="submit">Like</button>
            {% else %}
            <a class="btn btn-primary disabled">Like</a>
            {% endif %}
          </form>

            Bəyənmə: {{product.product_likes.all | length}}<br><br>

          {% if product in user_favorites %}
          <a class="btn btn-primary disabled">Səbətdə</a>
          {% else %}
          <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="choice" value="basket">
        <input type="hidden" name="productid" value="{{product.id}}">
        <button class="btn btn-primary" type="submit" style="width: 35%;">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
      </svg>
      
      Səbətə at </button>
      </form>
      {% endif %}

        </div>
      </div>
    </div>
  </div>
</div>



{% if request.user.is_authenticated %}
    <form class="container" method="POST">
        {% csrf_token %}
        <div class="mb-3 form-floating">
            <input type="hidden" name="choice" value="comment">
            <input type="hidden" name="productid" value="{{product.id}}">
            <textarea class="form-control" name="comment" placeholder="Leave a comment here" id="floatingTextarea"></textarea>
            <label for="floatingTextarea">Rəylərinizi yazın</label>
          </div>

        <button class="btn btn-primary" id="floatingTextarea">Send</button>  
    </form>
{% endif %}

<div class="container mt-3">
    <h4>Comments ({{product.product_comments.all | length}})</h4>
    {% for product_comment in product.product_comments.all %}
<div class="card">
    <div class="card-header">
      {{product_comment.user.username}}
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{product_comment.comment}}</p>
        <footer class="blockquote-footer">{{ product_comment.pub_date | datesince }}</footer>
      </blockquote>
    </div>
  </div>
  {% endfor %}
</div>    


  {% endblock %}  

templates/index.html
{% extends 'components/base.html' %}

{% block head %} <title>Index</title> {% endblock %}

{% block content %}
<p><div class="container" style="color: #ee0dee;"><h1>Məhsullarımız</h1></div></p>
<div class="container mt-5">
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for product in products %}
    <div class="col">
      <div class="card" style="width: 18rem;">
        {% if product.photo %}
        <a href="{% url 'product:detail' product.id %}"><img src="{{product.photo.url}}" class="card-img-top" alt="{{product.name}}"></a>
        {% endif %}
        <div class="card-body"  style="background-color: #f0e9e3; ">
          <h5 class="card-title">{{product}}</h5>
          <h5 class="card-title">{{product.price}} azn</h5>
          
          
          {% if product in user_favorites %}
          <a class="btn btn-primary disabled">Səbətdə</a>
          {% else %}
          <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="productid" value="{{product.id}}">
            <button class="btn btn-primary" type="submit" style="width: 50%;">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
          </svg>
          
          Səbətə at </button>
          </form>
          {% endif %}
          
          
          
        </div>
      </div>
      
    </div>
      {% endfor %} 
</div>
</div>  

   

{% endblock %}

templates/login.html
{% extends 'components/base.html' %}

{% block head%}<title>Login</title> {% endblock %}

{% block content %}

<div class="container mt-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="username">Username</label><br>
        <input type="text" name="username", id="username" style="width:50%"><br><br>
        <label for="password">Password</label><br>
        <input type="password" name="password", id="password" style="width:50%"><br><br>
        <button class="btn btn-primary" type="submit">Login</button>

    </form>

    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}

</div>




{% endblock %}

templates/register.html
{% extends 'components/base.html' %}

{% block head%}<title>Register</title> {% endblock %}

{% block content %}

<div class="container mt-5">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="username">Username</label><br>
        <input type="text" name="username", id="username" style="width:50%"><br><br>
        <label for="password">Password</label><br>
        <input type="password" name="password", id="password" style="width:50%"><br><br>
        <button class="btn btn-primary" type="submit">Register</button>

    </form>

    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}

</div>




{% endblock %}