account/urls.py
from django.urls import path, include
from account import views

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

ecommercepr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt import views as jwt_views
from product import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('account/', include('account.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/account/', include('account.api.urls')),
    path('api/product/', include('product.api.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path, include
from product import views

app_name = 'product'

urlpatterns = [
    path('detail/<int:id>/', views.DetailView.as_view(), name='detail'),
    path('basket/', views.BasketView.as_view(), name ="basket"),
    path('favorite_delete/<int:id>/', views.favorite_delete, name="favorite_delete"),
]

templates/components/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %} {% endblock %}
    <link rel="shortcut icon" href="code.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>


<body>
    {% include 'components/navbar.html' %}
    {% block content %} {% endblock %}  
    {% include "components/footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg " style="background-color: #c3b5e2; ">
  <div class="container-fluid">
    <a class="navbar-brand"  href="{% url 'index' %}"><b>Home</b></a>
          <div class="nav-item">{{request.user.username}}
          <a href="{% url 'product:basket' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="29" height="28" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
          </svg></a>
          {% if request.user.is_authenticated %}
          ({{request.user.user_favorites.all | length}})
          {% endif %}
        </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">


        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <b>Profil</b>
          </a>
          <ul class="dropdown-menu">
            {% if request.user.is_authenticated %}
            <li><a class="dropdown-item" href="#">{{request.user.username}}</a></li>
            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'account:login' %}">Login</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'account:register' %}">Register</a></li>
            {% endif %}
          </ul>
        </li>




      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>